import { Tree, Language } from 'tree-sitter' // Add Language to imports
import { Node, Edge } from '../types'

export interface IAnalysisStrategy {
  /**
   * Analyzes a tree-sitter Abstract Syntax Tree (AST) for a given file.
   * @param ast The AST generated by tree-sitter for the file's content.
   * @param filePath The absolute path to the file being analyzed.
   * @param language The tree-sitter language grammar used to parse the AST.
   */
  analyze(
    ast: Tree | { rootNode: { text: string } },
    filePath: string,
    language?: Language
  ): {
    nodes: Node[]
    edges: Edge[]
    exports?: Record<string, string>
    calls?: import('../types').CallSite[]
  }
}